name: Test Dispatch

on:
  schedule:
    - cron: '0 8 * * *'
    - cron: '0 13 * * *'
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "dispatch works"
